using System.Text;

namespace RepositoryFramework.Tools.TypescriptGenerator.Generation.TypeScript;

/// <summary>
/// Emits the DateMappers.ts utility file with parse/format functions
/// for converting between JSON date strings and JavaScript Date objects.
/// </summary>
public static class DateMapperEmitter
{
    /// <summary>
    /// The file name for the date mappers utility.
    /// </summary>
    public const string FileName = "DateMappers.ts";

    /// <summary>
    /// Generates the full content of the DateMappers.ts utility file.
    /// </summary>
    public static string Emit()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// ============================================");
        sb.AppendLine("// Date Mapping Utilities");
        sb.AppendLine("// Auto-generated by Rystem TypeScript Generator");
        sb.AppendLine("// ============================================");
        sb.AppendLine("//");
        sb.AppendLine("// Conversion functions between JSON date strings and JavaScript Date.");
        sb.AppendLine("// C# DateTime/DateTimeOffset/DateOnly serialize as ISO 8601 strings in JSON.");
        sb.AppendLine("// These utilities parse them into Date objects and format them back.");
        sb.AppendLine("// TimeOnly and TimeSpan remain as string (no JavaScript equivalent).");
        sb.AppendLine("// ============================================");
        sb.AppendLine();

        // DateTime
        sb.AppendLine("// --- DateTime ---");
        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine(" * Parses a C# DateTime ISO string into a JavaScript Date.");
        sb.AppendLine(" * @param value ISO 8601 string (e.g., \"2025-01-15T10:30:00Z\")");
        sb.AppendLine(" */");
        sb.AppendLine("export function parseDateTime(value: string): Date {");
        sb.AppendLine("  return new Date(value);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine(" * Formats a JavaScript Date back to a C# DateTime ISO string.");
        sb.AppendLine(" * @param date JavaScript Date object");
        sb.AppendLine(" */");
        sb.AppendLine("export function formatDateTime(date: Date): string {");
        sb.AppendLine("  return date.toISOString();");
        sb.AppendLine("}");
        sb.AppendLine();

        // DateTimeOffset
        sb.AppendLine("// --- DateTimeOffset ---");
        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine(" * Parses a C# DateTimeOffset ISO string into a JavaScript Date.");
        sb.AppendLine(" * @param value ISO 8601 string with offset (e.g., \"2025-01-15T10:30:00+01:00\")");
        sb.AppendLine(" */");
        sb.AppendLine("export function parseDateTimeOffset(value: string): Date {");
        sb.AppendLine("  return new Date(value);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine(" * Formats a JavaScript Date back to a C# DateTimeOffset ISO string.");
        sb.AppendLine(" * @param date JavaScript Date object");
        sb.AppendLine(" */");
        sb.AppendLine("export function formatDateTimeOffset(date: Date): string {");
        sb.AppendLine("  return date.toISOString();");
        sb.AppendLine("}");
        sb.AppendLine();

        // DateOnly
        sb.AppendLine("// --- DateOnly ---");
        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine(" * Parses a C# DateOnly string into a JavaScript Date (at midnight local time).");
        sb.AppendLine(" * @param value Date string (e.g., \"2025-01-15\")");
        sb.AppendLine(" */");
        sb.AppendLine("export function parseDateOnly(value: string): Date {");
        sb.AppendLine("  return new Date(value + 'T00:00:00');");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/**");
        sb.AppendLine(" * Formats a JavaScript Date back to a C# DateOnly string (YYYY-MM-DD).");
        sb.AppendLine(" * Uses local date components to avoid UTC timezone shifts.");
        sb.AppendLine(" * @param date JavaScript Date object");
        sb.AppendLine(" */");
        sb.AppendLine("export function formatDateOnly(date: Date): string {");
        sb.AppendLine("  const y = date.getFullYear();");
        sb.AppendLine("  const m = String(date.getMonth() + 1).padStart(2, '0');");
        sb.AppendLine("  const d = String(date.getDate()).padStart(2, '0');");
        sb.AppendLine("  return `${y}-${m}-${d}`;");
        sb.AppendLine("}");

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }
}
