using System.Text;
using RepositoryFramework.Tools.TypescriptGenerator.Domain;

namespace RepositoryFramework.Tools.TypescriptGenerator.Generation.Transformers;

/// <summary>
/// Emits ITransformer implementations for models and keys.
/// These transformers are used by RepositorySettings to convert between Raw and Clean types.
/// </summary>
public static class TransformerEmitter
{
    /// <summary>
    /// Emits a transformer file for a model or key type.
    /// </summary>
    public static string Emit(ModelDescriptor model, bool isKey = false)
    {
        if (model.IsEnum)
            return string.Empty;

        var sb = new StringBuilder();
        var baseName = model.GetBaseTypeName();
        var genericParams = model.GenericTypeParameters.Count > 0 
            ? $"<{string.Join(", ", model.GenericTypeParameters)}>" 
            : "";
        var typeName = $"{baseName}{genericParams}";
        var typeNameRaw = $"{baseName}Raw{genericParams}";
        var fileNameWithoutExt = model.GetFileName().Replace(".ts", "");
        var suffix = isKey ? "Key" : "";

        // Header
        sb.AppendLine("// ============================================");
        sb.AppendLine($"// {typeName} Transformer");
        sb.AppendLine("// Auto-generated by Rystem TypeScript Generator");
        sb.AppendLine("// ============================================");
        sb.AppendLine();

        // Imports
        sb.AppendLine("import type { ITransformer } from 'rystem.repository.client';");
        sb.AppendLine($"import type {{ {typeName}, {typeNameRaw} }} from '../types/{fileNameWithoutExt}';");
        sb.AppendLine($"import {{ mapRaw{typeName}To{typeName}, map{typeName}ToRaw{typeName} }} from '../types/{fileNameWithoutExt}';");
        sb.AppendLine();

        // Transformer implementation
        sb.AppendLine("/**");
        sb.AppendLine($" * Transformer for {typeName} type.");
        sb.AppendLine(" * Converts between Raw (JSON) and Clean (TypeScript) representations.");
        sb.AppendLine(" */");
        sb.AppendLine($"export const {baseName}Transformer{genericParams}: ITransformer<{typeName}> = {{");
        sb.AppendLine($"  fromPlain: (plain: {typeNameRaw}): {typeName} => mapRaw{typeName}To{typeName}(plain),");
        sb.AppendLine($"  toPlain: (instance: {typeName}): {typeNameRaw} => map{typeName}ToRaw{typeName}(instance),");
        sb.AppendLine("};");

        return sb.ToString();
    }

    /// <summary>
    /// Gets the file name for a transformer.
    /// </summary>
    public static string GetFileName(ModelDescriptor model)
    {
        return $"{model.GetBaseTypeName()}Transformer.ts";
    }
}
