using System.Text;
using RepositoryFramework.Tools.TypescriptGenerator.Domain;

namespace RepositoryFramework.Tools.TypescriptGenerator.Generation.Transformers;

/// <summary>
/// Emits ITransformer implementations for models and keys.
/// These transformers are used by RepositorySettings to convert between Raw and Clean types.
/// </summary>
public static class TransformerEmitter
{
    /// <summary>
    /// Emits a transformer file for a model or key type.
    /// </summary>
    public static string Emit(ModelDescriptor model, bool isKey = false)
    {
        if (model.IsEnum)
            return string.Empty;

        var sb = new StringBuilder();
        var name = model.Name;
        var suffix = isKey ? "Key" : "";

        // Header
        sb.AppendLine("// ============================================");
        sb.AppendLine($"// {name} Transformer");
        sb.AppendLine("// Auto-generated by Rystem TypeScript Generator");
        sb.AppendLine("// ============================================");
        sb.AppendLine();

        // Imports
        sb.AppendLine("import type { ITransformer } from 'rystem.repository.client';");
        sb.AppendLine($"import type {{ {name}, {name}Raw }} from '../types/{name.ToLowerInvariant()}';");
        sb.AppendLine($"import {{ mapRaw{name}To{name}, map{name}ToRaw{name} }} from '../types/{name.ToLowerInvariant()}';");
        sb.AppendLine();

        // Transformer implementation
        sb.AppendLine("/**");
        sb.AppendLine($" * Transformer for {name} type.");
        sb.AppendLine(" * Converts between Raw (JSON) and Clean (TypeScript) representations.");
        sb.AppendLine(" */");
        sb.AppendLine($"export const {name}Transformer: ITransformer<{name}> = {{");
        sb.AppendLine($"  fromPlain: (plain: {name}Raw): {name} => mapRaw{name}To{name}(plain),");
        sb.AppendLine($"  toPlain: (instance: {name}): {name}Raw => map{name}ToRaw{name}(instance),");
        sb.AppendLine("};");

        return sb.ToString();
    }

    /// <summary>
    /// Gets the file name for a transformer.
    /// </summary>
    public static string GetFileName(ModelDescriptor model)
    {
        return $"{model.Name}Transformer.ts";
    }
}
