using System.Text;

namespace RepositoryFramework.Tools.TypescriptGenerator.Generation.Services;

/// <summary>
/// Emits common TypeScript types used by services.
/// </summary>
public static class CommonTypesEmitter
{
    /// <summary>
    /// Generates common types file with State, Entity, BatchOperation, etc.
    /// </summary>
    public static string Emit()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// ============================================");
        sb.AppendLine("// Common Repository Types");
        sb.AppendLine("// Auto-generated by Rystem TypeScript Generator");
        sb.AppendLine("// ============================================");
        sb.AppendLine();

        // Entity type
        sb.AppendLine("/**");
        sb.AppendLine(" * Represents an entity with its key and value.");
        sb.AppendLine(" */");
        sb.AppendLine("export interface Entity<T, TKey> {");
        sb.AppendLine("  key: TKey;");
        sb.AppendLine("  value: T;");
        sb.AppendLine("}");
        sb.AppendLine();

        // State type
        sb.AppendLine("/**");
        sb.AppendLine(" * Represents the result state of a command operation.");
        sb.AppendLine(" */");
        sb.AppendLine("export interface State<T, TKey> {");
        sb.AppendLine("  isOk: boolean;");
        sb.AppendLine("  code?: number;");
        sb.AppendLine("  message?: string;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Raw State (for serialization)
        sb.AppendLine("/**");
        sb.AppendLine(" * Raw state from server response.");
        sb.AppendLine(" * @internal");
        sb.AppendLine(" */");
        sb.AppendLine("export interface RawState {");
        sb.AppendLine("  i: boolean;");
        sb.AppendLine("  c?: number;");
        sb.AppendLine("  m?: string;");
        sb.AppendLine("}");
        sb.AppendLine();

        // BatchOperation type
        sb.AppendLine("/**");
        sb.AppendLine(" * Represents a batch operation.");
        sb.AppendLine(" */");
        sb.AppendLine("export interface BatchOperation<T, TKey> {");
        sb.AppendLine("  command: BatchCommand;");
        sb.AppendLine("  key: TKey;");
        sb.AppendLine("  value?: T;");
        sb.AppendLine("}");
        sb.AppendLine();

        // BatchCommand enum
        sb.AppendLine("/**");
        sb.AppendLine(" * Batch operation command types.");
        sb.AppendLine(" */");
        sb.AppendLine("export enum BatchCommand {");
        sb.AppendLine("  Insert = 0,");
        sb.AppendLine("  Update = 1,");
        sb.AppendLine("  Delete = 2,");
        sb.AppendLine("}");
        sb.AppendLine();

        // Page type
        sb.AppendLine("/**");
        sb.AppendLine(" * Represents a paginated result.");
        sb.AppendLine(" */");
        sb.AppendLine("export interface Page<T, TKey> {");
        sb.AppendLine("  items: Entity<T, TKey>[];");
        sb.AppendLine("  totalCount: number;");
        sb.AppendLine("  pageNumber: number;");
        sb.AppendLine("  pageSize: number;");
        sb.AppendLine("  totalPages: number;");
        sb.AppendLine("}");
        sb.AppendLine();

        // QueryOptions type
        sb.AppendLine("/**");
        sb.AppendLine(" * Options for query operations.");
        sb.AppendLine(" */");
        sb.AppendLine("export interface QueryOptions {");
        sb.AppendLine("  filter?: string;");
        sb.AppendLine("  order?: string;");
        sb.AppendLine("  top?: number;");
        sb.AppendLine("  skip?: number;");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Gets the filename for common types.
    /// </summary>
    public static string GetFileName() => "common.ts";
}
