using System.Text;
using RepositoryFramework.Tools.TypescriptGenerator.Domain;
using RepositoryFramework.Tools.TypescriptGenerator.Generation.TypeScript;

namespace RepositoryFramework.Tools.TypescriptGenerator.Generation.Services;

/// <summary>
/// Generates a complete service file with all imports, types, and service class.
/// </summary>
public class ServiceFileGenerator
{
    private readonly EmitterContext _context;

    public ServiceFileGenerator(EmitterContext context)
    {
        _context = context;
    }

    /// <summary>
    /// Generates a complete service file content for a repository.
    /// </summary>
    public string Generate(
        RepositoryDescriptor repository,
        ModelDescriptor model,
        ModelDescriptor? key)
    {
        var sb = new StringBuilder();

        // Header comment
        sb.AppendLine("// ============================================");
        sb.AppendLine($"// {repository.FactoryName} Service");
        sb.AppendLine("// Auto-generated by Rystem TypeScript Generator");
        sb.AppendLine("// ============================================");
        sb.AppendLine();

        // Generate imports
        var imports = GenerateImports(repository, model, key);
        sb.Append(imports);
        sb.AppendLine();

        // Generate service class
        var serviceCode = ServiceEmitter.Emit(repository, model, key, _context);
        sb.Append(serviceCode);

        return sb.ToString();
    }

    private string GenerateImports(
        RepositoryDescriptor repository,
        ModelDescriptor model,
        ModelDescriptor? key)
    {
        var sb = new StringBuilder();
        var modelFile = $"./{model.Name.ToLowerInvariant()}";
        var requiresRaw = model.RequiresRawType;
        var keyRequiresRaw = key?.RequiresRawType ?? false;

        // Import common types
        sb.AppendLine("import { Entity, State, RawState, BatchOperation, BatchCommand, QueryOptions } from './common';");

        // Import model types
        var modelImports = new List<string> { model.Name };
        if (requiresRaw)
        {
            modelImports.Add($"{model.Name}Raw");
            modelImports.Add($"mapRaw{model.Name}To{model.Name}");
            modelImports.Add($"map{model.Name}ToRaw{model.Name}");
        }
        sb.AppendLine($"import {{ {string.Join(", ", modelImports)} }} from '../types/{model.Name.ToLowerInvariant()}';");

        // Import key types if complex
        if (key != null && !repository.IsPrimitiveKey)
        {
            var keyImports = new List<string> { key.Name };
            if (keyRequiresRaw)
            {
                keyImports.Add($"{key.Name}Raw");
                keyImports.Add($"mapRaw{key.Name}To{key.Name}");
                keyImports.Add($"map{key.Name}ToRaw{key.Name}");
            }
            sb.AppendLine($"import {{ {string.Join(", ", keyImports)} }} from '../types/{key.Name.ToLowerInvariant()}';");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Gets the filename for a service.
    /// </summary>
    public static string GetFileName(RepositoryDescriptor repository)
        => $"{repository.FactoryName.ToLowerInvariant()}.service.ts";
}
