using System.Text;
using RepositoryFramework.Tools.TypescriptGenerator.Domain;

namespace RepositoryFramework.Tools.TypescriptGenerator.Generation.Services;

/// <summary>
/// Generates a factory/registry for accessing all services.
/// </summary>
public static class ServiceRegistryEmitter
{
    /// <summary>
    /// Generates a service registry that provides access to all generated services.
    /// </summary>
    public static string Emit(IEnumerable<RepositoryDescriptor> repositories)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// ============================================");
        sb.AppendLine("// Service Registry");
        sb.AppendLine("// Auto-generated by Rystem TypeScript Generator");
        sb.AppendLine("// ============================================");
        sb.AppendLine();

        // Generate imports
        foreach (var repo in repositories)
        {
            var serviceName = $"{repo.FactoryName}Service";
            sb.AppendLine($"import {{ {serviceName} }} from './{repo.FactoryName.ToLowerInvariant()}.service';");
        }
        sb.AppendLine();

        // Re-export services
        sb.AppendLine("// Re-export all services");
        foreach (var repo in repositories)
        {
            var serviceName = $"{repo.FactoryName}Service";
            sb.AppendLine($"export {{ {serviceName} }};");
        }
        sb.AppendLine();

        // Export common types
        sb.AppendLine("// Re-export common types");
        sb.AppendLine("export { Entity, State, BatchOperation, BatchCommand, QueryOptions, Page } from './common';");
        sb.AppendLine();

        // Generate configuration interface
        sb.AppendLine("/**");
        sb.AppendLine(" * Configuration for service initialization.");
        sb.AppendLine(" */");
        sb.AppendLine("export interface ServiceConfig {");
        sb.AppendLine("  baseUrl: string;");
        sb.AppendLine("  headers?: () => Promise<HeadersInit>;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Generate registry class
        sb.AppendLine("/**");
        sb.AppendLine(" * Service registry for accessing all repository services.");
        sb.AppendLine(" */");
        sb.AppendLine("export class Services {");
        sb.AppendLine("  private static config: ServiceConfig | null = null;");
        sb.AppendLine("  private static instances: Map<string, unknown> = new Map();");
        sb.AppendLine();

        // Configure method
        sb.AppendLine("  /**");
        sb.AppendLine("   * Configures the services with base URL and optional headers provider.");
        sb.AppendLine("   */");
        sb.AppendLine("  static configure(config: ServiceConfig): void {");
        sb.AppendLine("    Services.config = config;");
        sb.AppendLine("    Services.instances.clear();");
        sb.AppendLine("  }");
        sb.AppendLine();

        // Check configuration helper
        sb.AppendLine("  private static ensureConfigured(): ServiceConfig {");
        sb.AppendLine("    if (!Services.config) {");
        sb.AppendLine("      throw new Error('Services not configured. Call Services.configure() first.');");
        sb.AppendLine("    }");
        sb.AppendLine("    return Services.config;");
        sb.AppendLine("  }");
        sb.AppendLine();

        // Generate getters for each service
        foreach (var repo in repositories)
        {
            var serviceName = $"{repo.FactoryName}Service";
            var factoryName = repo.FactoryName;
            var instanceKey = factoryName.ToLowerInvariant();

            sb.AppendLine($"  /**");
            sb.AppendLine($"   * Gets the {factoryName} service instance.");
            sb.AppendLine($"   */");
            sb.AppendLine($"  static get {factoryName}(): {serviceName} {{");
            sb.AppendLine($"    const config = Services.ensureConfigured();");
            sb.AppendLine($"    if (!Services.instances.has('{instanceKey}')) {{");
            sb.AppendLine($"      Services.instances.set('{instanceKey}', new {serviceName}(");
            sb.AppendLine($"        `${{config.baseUrl}}/api/{factoryName}`,");
            sb.AppendLine($"        config.headers");
            sb.AppendLine($"      ));");
            sb.AppendLine($"    }}");
            sb.AppendLine($"    return Services.instances.get('{instanceKey}') as {serviceName};");
            sb.AppendLine($"  }}");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Gets the filename for the service registry.
    /// </summary>
    public static string GetFileName() => "index.ts";
}
