using RepositoryFramework.Tools.TypescriptGenerator.Generation.Services;
using Xunit;

namespace RepositoryFramework.UnitTest.TypescriptGenerator;

/// <summary>
/// Tests for CommonTypesEmitter - generating common TypeScript types.
/// </summary>
public class CommonTypesEmitterTest
{
    [Fact]
    public void Emit_GeneratesEntityInterface()
    {
        // Act
        var result = CommonTypesEmitter.Emit();

        // Assert
        Assert.Contains("export interface Entity<T, TKey>", result);
        Assert.Contains("key: TKey;", result);
        Assert.Contains("value: T;", result);
    }

    [Fact]
    public void Emit_GeneratesStateInterface()
    {
        // Act
        var result = CommonTypesEmitter.Emit();

        // Assert
        Assert.Contains("export interface State<T, TKey>", result);
        Assert.Contains("isOk: boolean;", result);
        Assert.Contains("code?: number;", result);
        Assert.Contains("message?: string;", result);
    }

    [Fact]
    public void Emit_GeneratesRawStateInterface()
    {
        // Act
        var result = CommonTypesEmitter.Emit();

        // Assert
        Assert.Contains("export interface RawState", result);
        Assert.Contains("i: boolean;", result);
        Assert.Contains("c?: number;", result);
        Assert.Contains("m?: string;", result);
    }

    [Fact]
    public void Emit_GeneratesBatchOperationInterface()
    {
        // Act
        var result = CommonTypesEmitter.Emit();

        // Assert
        Assert.Contains("export interface BatchOperation<T, TKey>", result);
        Assert.Contains("command: BatchCommand;", result);
        Assert.Contains("key: TKey;", result);
        Assert.Contains("value?: T;", result);
    }

    [Fact]
    public void Emit_GeneratesBatchCommandEnum()
    {
        // Act
        var result = CommonTypesEmitter.Emit();

        // Assert
        Assert.Contains("export enum BatchCommand", result);
        Assert.Contains("Insert = 0", result);
        Assert.Contains("Update = 1", result);
        Assert.Contains("Delete = 2", result);
    }

    [Fact]
    public void Emit_GeneratesPageInterface()
    {
        // Act
        var result = CommonTypesEmitter.Emit();

        // Assert
        Assert.Contains("export interface Page<T, TKey>", result);
        Assert.Contains("items: Entity<T, TKey>[];", result);
        Assert.Contains("totalCount: number;", result);
        Assert.Contains("pageNumber: number;", result);
        Assert.Contains("pageSize: number;", result);
        Assert.Contains("totalPages: number;", result);
    }

    [Fact]
    public void Emit_GeneratesQueryOptionsInterface()
    {
        // Act
        var result = CommonTypesEmitter.Emit();

        // Assert
        Assert.Contains("export interface QueryOptions", result);
        Assert.Contains("filter?: string;", result);
        Assert.Contains("order?: string;", result);
        Assert.Contains("top?: number;", result);
        Assert.Contains("skip?: number;", result);
    }

    [Fact]
    public void Emit_ContainsAutoGeneratedComment()
    {
        // Act
        var result = CommonTypesEmitter.Emit();

        // Assert
        Assert.Contains("Auto-generated by Rystem TypeScript Generator", result);
    }

    [Fact]
    public void GetFileName_ReturnsCommonTs()
    {
        // Act
        var fileName = CommonTypesEmitter.GetFileName();

        // Assert
        Assert.Equal("common.ts", fileName);
    }
}
