using RepositoryFramework.Tools.TypescriptGenerator.Domain;
using RepositoryFramework.Tools.TypescriptGenerator.Generation.Transformers;
using Xunit;

namespace RepositoryFramework.UnitTest.TypescriptGenerator;

/// <summary>
/// Tests for TransformerEmitter - generates ITransformer implementations.
/// </summary>
public class TransformerEmitterTest
{
    [Fact]
    public void Emit_GeneratesTransformerConst()
    {
        // Arrange
        var model = TestDescriptorFactory.CreateModel("Calendar");

        // Act
        var result = TransformerEmitter.Emit(model);

        // Assert
        Assert.Contains("export const CalendarTransformer: ITransformer<Calendar>", result);
    }

    [Fact]
    public void Emit_ImportsITransformer()
    {
        // Arrange
        var model = TestDescriptorFactory.CreateModel("Calendar");

        // Act
        var result = TransformerEmitter.Emit(model);

        // Assert
        Assert.Contains("import type { ITransformer } from 'rystem.repository.client';", result);
    }

    [Fact]
    public void Emit_ImportsTypesWithImportType()
    {
        // Arrange
        var model = TestDescriptorFactory.CreateModel("Calendar");

        // Act
        var result = TransformerEmitter.Emit(model);

        // Assert
        Assert.Contains("import type { Calendar, CalendarRaw } from '../types/calendar';", result);
    }

    [Fact]
    public void Emit_ImportsMappersNormally()
    {
        // Arrange
        var model = TestDescriptorFactory.CreateModel("Calendar");

        // Act
        var result = TransformerEmitter.Emit(model);

        // Assert
        Assert.Contains("import { mapRawCalendarToCalendar, mapCalendarToRawCalendar } from '../types/calendar';", result);
    }

    [Fact]
    public void Emit_ImplementsFromPlain()
    {
        // Arrange
        var model = TestDescriptorFactory.CreateModel("Calendar");

        // Act
        var result = TransformerEmitter.Emit(model);

        // Assert
        Assert.Contains("fromPlain: (plain: CalendarRaw): Calendar => mapRawCalendarToCalendar(plain)", result);
    }

    [Fact]
    public void Emit_ImplementsToPlain()
    {
        // Arrange
        var model = TestDescriptorFactory.CreateModel("Calendar");

        // Act
        var result = TransformerEmitter.Emit(model);

        // Assert
        Assert.Contains("toPlain: (instance: Calendar): CalendarRaw => mapCalendarToRawCalendar(instance)", result);
    }

    [Fact]
    public void Emit_EnumModel_ReturnsEmpty()
    {
        // Arrange
        var enumModel = TestDescriptorFactory.CreateEnum("Status", ("Active", 0), ("Inactive", 1));

        // Act
        var result = TransformerEmitter.Emit(enumModel);

        // Assert
        Assert.Empty(result);
    }

    [Fact]
    public void Emit_KeyModel_GeneratesTransformer()
    {
        // Arrange
        var keyModel = TestDescriptorFactory.CreateModel("LeagueKey");

        // Act
        var result = TransformerEmitter.Emit(keyModel, isKey: true);

        // Assert
        Assert.Contains("export const LeagueKeyTransformer: ITransformer<LeagueKey>", result);
        Assert.Contains("fromPlain:", result);
        Assert.Contains("toPlain:", result);
    }

    [Fact]
    public void GetFileName_ReturnsCorrectName()
    {
        // Arrange
        var model = TestDescriptorFactory.CreateModel("Calendar");

        // Act
        var fileName = TransformerEmitter.GetFileName(model);

        // Assert
        Assert.Equal("CalendarTransformer.ts", fileName);
    }

    [Fact]
    public void Emit_IncludesHeader()
    {
        // Arrange
        var model = TestDescriptorFactory.CreateModel("Calendar");

        // Act
        var result = TransformerEmitter.Emit(model);

        // Assert
        Assert.Contains("// ============================================", result);
        Assert.Contains("// Calendar Transformer", result);
        Assert.Contains("// Auto-generated by Rystem TypeScript Generator", result);
    }

    [Fact]
    public void Emit_IncludesJsDoc()
    {
        // Arrange
        var model = TestDescriptorFactory.CreateModel("Calendar");

        // Act
        var result = TransformerEmitter.Emit(model);

        // Assert
        Assert.Contains("/**", result);
        Assert.Contains("* Transformer for Calendar type.", result);
        Assert.Contains("* Converts between Raw (JSON) and Clean (TypeScript) representations.", result);
        Assert.Contains("*/", result);
    }
}
