import { ClientInteractionRequest } from "./ClientInteractionRequest";

/**
 * Response status from PlayFramework execution.
 * Matches all 18 C# AiResponseStatus enum values (serialized as camelCase via JsonStringEnumConverter).
 */
export type AiResponseStatus =
    | "initializing"
    | "loadingCache"
    | "executingMainActors"
    | "planning"
    | "executingScene"
    | "functionRequest"
    | "functionCompleted"
    | "toolSkipped"
    | "streaming"
    | "running"
    | "summarizing"
    | "directorDecision"
    | "generatingFinalResponse"
    | "savingCache"
    | "savingMemory"
    | "awaitingClient"
    | "completed"
    | "budgetExceeded"
    | "error";

/**
 * Single step response from PlayFramework (used in step-by-step streaming).
 * Matches C# AiSceneResponse contract.
 */
export interface AiSceneResponse {
    /**
     * Execution status.
     */
    status: AiResponseStatus;

    /**
     * Scene name (if applicable).
     */
    sceneName?: string;

    /**
     * Function/tool name that was called (if applicable).
     */
    functionName?: string;

    /**
     * Function/tool arguments (if applicable).
     */
    functionArguments?: string;

    /**
     * Response message/text.
     */
    message?: string;

    /**
     * Streaming chunk — the new piece of text received in this streaming event.
     * Only populated when status is "Streaming".
     */
    streamingChunk?: string;

    /**
     * Indicates if this is the last chunk in a streaming response.
     */
    isStreamingComplete?: boolean;

    /**
     * Error message (if status === "Error").
     */
    errorMessage?: string;

    /**
     * Input tokens used in this operation.
     */
    inputTokens?: number;

    /**
     * Cached input tokens (reduced cost).
     */
    cachedInputTokens?: number;

    /**
     * Output tokens generated in this operation.
     */
    outputTokens?: number;

    /**
     * Total tokens (input + cached + output).
     */
    totalTokens?: number;

    /**
     * Cost of this specific operation.
     */
    cost?: number;

    /**
     * Cumulative cost so far in the execution.
     */
    totalCost?: number;

    /**
     * Conversation key for resuming execution.
     */
    conversationKey?: string;

    /**
     * Continuation token for resuming after client interaction.
     * Present when status === "AwaitingClient".
     */
    continuationToken?: string;

    /**
     * Client interaction request when status === "AwaitingClient".
     * Contains tool name, arguments, and schema for client execution.
     */
    clientInteractionRequest?: ClientInteractionRequest;

    /**
     * Timestamp of this response (ISO 8601).
     */
    timestamp?: string;

    /**
     * Additional metadata.
     */
    metadata?: Record<string, any>;

    /**
     * Multi-modal output contents (images, audio, files generated by LLM or tools).
     * Each item has { type, text, data, mediaType } matching ClientContentItem.
     */
    contents?: Array<{
        type: string;
        text?: string;
        data?: string;
        mediaType?: string;
    }>;
}

/**
 * Completion marker for SSE streaming.
 */
export interface CompletionMarker {
    status: "completed";
}

/**
 * Error marker for SSE streaming.
 */
export interface ErrorMarker {
    status: "error";
    errorMessage: string;
}

/**
 * SSE event types.
 */
export type SSEEvent = AiSceneResponse | CompletionMarker | ErrorMarker;
