using Microsoft.Extensions.AI;

namespace Rystem.PlayFramework;

/// <summary>
/// Represents a response from a scene execution.
/// </summary>
public sealed class AiSceneResponse
{
    /// <summary>
    /// Current status of the execution.
    /// </summary>
    public AiResponseStatus Status { get; set; }

    /// <summary>
    /// Scene name (if applicable).
    /// </summary>
    public string? SceneName { get; set; }

    /// <summary>
    /// Function/tool name that was called (if applicable).
    /// </summary>
    public string? FunctionName { get; set; }

    /// <summary>
    /// Function/tool arguments (if applicable).
    /// </summary>
    public string? FunctionArguments { get; set; }

    /// <summary>
    /// Response message from AI or tool execution.
    /// </summary>
    public string? Message { get; set; }

    /// <summary>
    /// Streaming chunk - the new piece of text received in this streaming event.
    /// Only populated when Status is Streaming.
    /// </summary>
    public string? StreamingChunk { get; set; }

    /// <summary>
    /// Indicates if this is the last chunk in a streaming response.
    /// </summary>
    public bool IsStreamingComplete { get; set; }

    /// <summary>
    /// Error message (if Status is Error).
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Input tokens used in this operation.
    /// </summary>
    public int? InputTokens { get; set; }

    /// <summary>
    /// Cached input tokens (10% cost).
    /// </summary>
    public int? CachedInputTokens { get; set; }

    /// <summary>
    /// Output tokens generated in this operation.
    /// </summary>
    public int? OutputTokens { get; set; }

    /// <summary>
    /// Total tokens (input + cached + output).
    /// </summary>
    public int? TotalTokens { get; set; }

    /// <summary>
    /// Cost of this specific operation (null if no LLM call).
    /// </summary>
    public decimal? Cost { get; set; }

    /// <summary>
    /// Cumulative cost so far in the execution.
    /// </summary>
    public decimal TotalCost { get; set; }

    /// <summary>
    /// Conversation key for this execution.
    /// Used to track and resume conversations.
    /// </summary>
    public string? ConversationKey { get; set; }

    /// <summary>
    /// Continuation token for resuming execution after client interaction.
    /// Only present when Status is AwaitingClient.
    /// Client must send this back with ClientInteractionResults to resume.
    /// </summary>
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// Request for client-side tool execution.
    /// Only present when Status is AwaitingClient.
    /// Client must execute the tool and return result with continuation token.
    /// </summary>
    public ClientInteractionRequest? ClientInteractionRequest { get; set; }

    /// <summary>
    /// Timestamp of this response.
    /// </summary>
    public DateTimeOffset Timestamp { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Additional metadata.
    /// </summary>
    public Dictionary<string, object> Metadata { get; set; } = [];

    /// <summary>
    /// Multi-modal output contents (images, audio, files generated by LLM or tools).
    /// </summary>
    public IEnumerable<AIContent>? Contents { get; set; }

    /// <summary>
    /// Check if response contains image content
    /// </summary>
    public bool HasImage => Contents?.OfType<DataContent>()
        .Any(c => c.MediaType?.StartsWith("image/", StringComparison.OrdinalIgnoreCase) == true) == true;

    /// <summary>
    /// Check if response contains audio content
    /// </summary>
    public bool HasAudio => Contents?.OfType<DataContent>()
        .Any(c => c.MediaType?.StartsWith("audio/", StringComparison.OrdinalIgnoreCase) == true) == true;

    /// <summary>
    /// Get first image content from response
    /// </summary>
    public DataContent? GetImage() => Contents?.OfType<DataContent>()
        .FirstOrDefault(c => c.MediaType?.StartsWith("image/", StringComparison.OrdinalIgnoreCase) == true);

    /// <summary>
    /// Get first audio content from response
    /// </summary>
    public DataContent? GetAudio() => Contents?.OfType<DataContent>()
        .FirstOrDefault(c => c.MediaType?.StartsWith("audio/", StringComparison.OrdinalIgnoreCase) == true);

    /// <summary>
    /// Check if response contains video content
    /// </summary>
    public bool HasVideo => Contents?.OfType<DataContent>()
        .Any(c => c.MediaType?.StartsWith("video/", StringComparison.OrdinalIgnoreCase) == true) == true;

    /// <summary>
    /// Get first video content from response
    /// </summary>
    public DataContent? GetVideo() => Contents?.OfType<DataContent>()
        .FirstOrDefault(c => c.MediaType?.StartsWith("video/", StringComparison.OrdinalIgnoreCase) == true);

    /// <summary>
    /// Check if response contains file content (non-image/audio/video)
    /// </summary>
    public bool HasFile => Contents?.OfType<DataContent>()
        .Any(c => !string.IsNullOrEmpty(c.MediaType) && 
                  !c.MediaType.StartsWith("image/", StringComparison.OrdinalIgnoreCase) &&
                  !c.MediaType.StartsWith("audio/", StringComparison.OrdinalIgnoreCase) &&
                  !c.MediaType.StartsWith("video/", StringComparison.OrdinalIgnoreCase)) == true;

    /// <summary>
    /// Get first file content (non-image/audio/video) from response
    /// </summary>
    public DataContent? GetFile() => Contents?.OfType<DataContent>()
        .FirstOrDefault(c => !string.IsNullOrEmpty(c.MediaType) && 
                             !c.MediaType.StartsWith("image/", StringComparison.OrdinalIgnoreCase) &&
                             !c.MediaType.StartsWith("audio/", StringComparison.OrdinalIgnoreCase) &&
                             !c.MediaType.StartsWith("video/", StringComparison.OrdinalIgnoreCase));

    /// <summary>
    /// Get all image contents from response
    /// </summary>
    public IEnumerable<DataContent> GetAllImages() => Contents?.OfType<DataContent>()
        .Where(c => c.MediaType?.StartsWith("image/", StringComparison.OrdinalIgnoreCase) == true) ?? [];

    /// <summary>
    /// Get all audio contents from response
    /// </summary>
    public IEnumerable<DataContent> GetAllAudios() => Contents?.OfType<DataContent>()
        .Where(c => c.MediaType?.StartsWith("audio/", StringComparison.OrdinalIgnoreCase) == true) ?? [];

    /// <summary>
    /// Get all video contents from response
    /// </summary>
    public IEnumerable<DataContent> GetAllVideos() => Contents?.OfType<DataContent>()
        .Where(c => c.MediaType?.StartsWith("video/", StringComparison.OrdinalIgnoreCase) == true) ?? [];

    /// <summary>
    /// Get all file contents (non-image/audio/video) from response
    /// </summary>
    public IEnumerable<DataContent> GetAllFiles() => Contents?.OfType<DataContent>()
        .Where(c => !string.IsNullOrEmpty(c.MediaType) && 
                    !c.MediaType.StartsWith("image/", StringComparison.OrdinalIgnoreCase) &&
                    !c.MediaType.StartsWith("audio/", StringComparison.OrdinalIgnoreCase) &&
                    !c.MediaType.StartsWith("video/", StringComparison.OrdinalIgnoreCase)) ?? [];

    /// <summary>
    /// Check if response contains URI content
    /// </summary>
    public bool HasUri => Contents?.OfType<UriContent>().Any() == true;

    /// <summary>
    /// Get first URI content from response
    /// </summary>
    public UriContent? GetUri() => Contents?.OfType<UriContent>().FirstOrDefault();

    /// <summary>
    /// Get all URI contents from response
    /// </summary>
    public IEnumerable<UriContent> GetAllUris() => Contents?.OfType<UriContent>() ?? [];
}
