name: Rystem.BackgroundJob.Nuget
on:
  push:
    branches:
      - master
    paths:
      - src/Extensions/BackgroundJob/Rystem.BackgroundJob/Rystem.BackgroundJob.csproj
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: Rystem.Nuget
    
    steps:
      - name: Publish package
        uses: KeyserDSoze/DefaultAction/pushing_nuget_with_symbols@v1.0.1
        with:
          dotnet-version: ${{ secrets.NET_VERSION }}
          path: src/Extensions/BackgroundJob/Rystem.BackgroundJob/Rystem.BackgroundJob.csproj
          api-key: ${{ secrets.NUGET_API_KEY }}