name: Api.Server.Nuget
on:
  push:
    branches:
      - master
    paths:
      - src/Repository/RepositoryFramework.Api.Server/RepositoryFramework.Api.Server.csproj
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: RepositoryFramework
    
    steps:
      - name: Publish package
        uses: KeyserDSoze/DefaultAction/pushing_nuget_with_symbols@v1.0.1
        with:
          dotnet-version: "7.x"
          path: src/Repository/RepositoryFramework.Api.Server/RepositoryFramework.Api.Server.csproj
          api-key: ${{ secrets.NUGET_API_KEY }}