name: Cache.Nuget
on:
  push:
    branches:
      - master
    paths:
      - src/Repository/RepositoryFramework.Cache/RepositoryFramework.Cache/RepositoryFramework.Cache.csproj
      - reload.txt
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: Rystem.Nuget
    
    steps:
      - name: Publish package
        uses: KeyserDSoze/DefaultAction/pushing_nuget_with_symbols@v1.0.1
        with:
          dotnet-version: "7.x"
          path: src/Repository/RepositoryFramework.Cache/RepositoryFramework.Cache/RepositoryFramework.Cache.csproj
          api-key: ${{ secrets.NUGET_API_KEY }}