name: Web.Components
on:
  push:
    branches:
      - master
    paths:
      - src/Repository/RepositoryFramework.Web/RepositoryFramework.Web.Components/RepositoryFramework.Web.Components.csproj
      - reload.txt
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: Rystem.Nuget
    
    steps:
      - name: Publish package
        uses: KeyserDSoze/DefaultAction/pushing_nuget_with_symbols@v.1.0.2
        with:
          dotnet-version: ${{ secrets.NET_VERSION }}
          path: src/Repository/RepositoryFramework.Web/RepositoryFramework.Web.Components/RepositoryFramework.Web.Components.csproj
          api-key: ${{ secrets.NUGET_API_KEY }}