name: SonarLint.Rystem
on:
  push:
    branches:
      - master
  issue_comment:
    types: [created, edited, deleted]
jobs:
  analyze:
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, '/sonar') 
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 1.11
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
            path: ~\sonar\cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
            path: .\.sonar\scanner
            key: ${{ runner.os }}-sonar-scanner
            restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
            dotnet tool install --global dotnet-coverage
            New-Item -Path .\.sonar\scanner -ItemType Directory
            dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
            .\.sonar\scanner\dotnet-sonarscanner begin /k:"KeyserDSoze_Rystem" /o:"keyserdsoze" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
            dotnet build "src/Core/Rystem/Rystem.csproj" -c Debug
            dotnet build "src/Extensions/BackgroundJob/Rystem.BackgroundJob/Rystem.BackgroundJob.csproj" -c Debug
            dotnet build "src/Extensions/Concurrency/Rystem.Concurrency/Rystem.Concurrency.csproj" -c Debug
            dotnet build "src/Extensions/Queue/Rystem.Queue/Rystem.Queue.csproj" -c Debug
            dotnet build "src/Extensions/XUnitTest/Rystem.XUnitTest/Rystem.XUnitTest.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Abstractions/RepositoryFramework.Abstractions.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Api.Client/RepositoryFramework.Api.Client.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Api.Server/RepositoryFramework.Api.Server.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Infrastructure.InMemory/RepositoryFramework.Infrastructure.InMemory.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.MigrationTools/RepositoryFramework.MigrationTools.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Cache/RepositoryFramework.Cache/RepositoryFramework.Cache.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Cache/RepositoryFramework.Cache.Azure.Storage.Blob/RepositoryFramework.Cache.Azure.Storage.Blob.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Infrastructures/RepositoryFramework.Infrastructure.Azure.Cosmos.Sql/RepositoryFramework.Infrastructure.Azure.Cosmos.Sql.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Infrastructures/RepositoryFramework.Infrastructure.Azure.Storage.Blob/RepositoryFramework.Infrastructure.Azure.Storage.Blob.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Infrastructures/RepositoryFramework.Infrastructure.Azure.Storage.Table/RepositoryFramework.Infrastructure.Azure.Storage.Table.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Infrastructures/RepositoryFramework.Infrastructure.Dynamics.Dataverse/RepositoryFramework.Infrastructure.Dynamics.Dataverse.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Infrastructures/RepositoryFramework.Infrastructure.EntityFramework/RepositoryFramework.Infrastructure.EntityFramework.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Infrastructures/RepositoryFramework.Infrastructure.MsSql/RepositoryFramework.Infrastructure.MsSql.csproj" -c Debug
            dotnet build "src/Repository/RepositoryFramework.Web/RepositoryFramework.Web.Components/RepositoryFramework.Web.Components.csproj" -c Debug
            dotnet test "src/Repository/RepositoryFramework.Test/RepositoryFramework.UnitTest/RepositoryFramework.UnitTest.csproj" -c Debug --no-build /p:CollectCoverage=true /p:CoverletOutput=$root\coverage /p:CoverletOutputFormat=opencover
            .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"